import { StyleSheet } from 'react-native';
import { theme, space, radius, type } from '../theme/tokens';

export const styles = StyleSheet.create({
  flex: {
    flex: 1,
    backgroundColor: theme.bgPage,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollContent: {
    paddingBottom: 112,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: space[6],
  },
  logo: {
    width: 120,
    aspectRatio: 1376 / 768,
  },
  headerActions: {
    flexDirection: 'row',
    gap: space[3],
  },
  bellWrap: {
    width: 44,
    height: 44,
  },
  bellButton: {
    width: 44,
    height: 44,
    borderRadius: radius.full,
    backgroundColor: theme.bgRaised,
    borderWidth: 1,
    borderColor: theme.borderDefault,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bellBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    width: 18,
    height: 18,
    borderRadius: radius.full,
    backgroundColor: theme.statusDanger,
    borderWidth: 2,
    borderColor: theme.bgPage,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bellBadgeText: {
    fontSize: 11,
    fontFamily: 'Urbanist_700Bold',
    color: theme.textInverse,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: radius.full,
    backgroundColor: theme.brandSubtle,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontSize: 13,
    fontFamily: 'Urbanist_700Bold',
    color: theme.brandDefault,
  },
  scopeRow: {
    flexDirection: 'row',
    gap: space[3],
    marginTop: space[4],
    paddingHorizontal: space[6],
  },
  scopePill: {
    flex: 1,
    height: 40,
    paddingHorizontal: space[3],
    backgroundColor: theme.bgRaised,
    borderWidth: 1,
    borderColor: theme.borderDefault,
    borderRadius: radius.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: space[1] + 2,
  },
  scopePillText: {
    flex: 1,
    fontSize: 13,
    fontFamily: 'Urbanist_600SemiBold',
    color: theme.textPrimary,
  },
  searchBar: {
    marginTop: space[4],
    marginHorizontal: space[6],
    height: 44,
    paddingHorizontal: space[3],
    backgroundColor: theme.bgRaised,
    borderWidth: 1,
    borderColor: theme.borderDefault,
    borderRadius: radius.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: space[2],
  },
  searchPlaceholder: {
    ...type.body,
    color: theme.textTertiary,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    marginTop: space[6],
    paddingHorizontal: space[6],
  },
  sectionHeaderTitle: {
    ...type.h3,
    color: theme.textPrimary,
  },
  showAll: {
    fontSize: 13,
    fontFamily: 'Urbanist_600SemiBold',
    color: theme.brandDefault,
  },
  kpiGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: space[3],
    marginTop: space[3],
    paddingHorizontal: space[6],
  },
  kpiCard: {
    width: '47%',
    flexGrow: 1,
    backgroundColor: theme.bgRaised,
    borderWidth: 1,
    borderColor: theme.borderSubtle,
    borderRadius: radius.lg,
    padding: space[4],
  },
  kpiLabel: {
    fontSize: 13,
    fontFamily: 'Urbanist_600SemiBold',
    color: theme.textSecondary,
    marginTop: space[2],
  },
  kpiValue: {
    fontSize: 28,
    fontFamily: 'Urbanist_700Bold',
    color: theme.textPrimary,
    marginTop: space[1],
  },
  kpiBadge: {
    alignSelf: 'flex-start',
    height: 20,
    paddingHorizontal: space[2],
    borderRadius: radius.full,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: space[2],
  },
  kpiBadgeText: {
    fontSize: 12,
    fontFamily: 'Urbanist_600SemiBold',
  },
  groupList: {
    gap: space[5],
    marginTop: space[6],
    paddingHorizontal: space[6],
  },
  groupLabel: {
    fontSize: 13,
    fontFamily: 'Urbanist_600SemiBold',
    letterSpacing: 0.26,
    color: theme.textSecondary,
    marginBottom: space[2],
  },
  groupCard: {
    backgroundColor: theme.bgRaised,
    borderWidth: 1,
    borderColor: theme.borderSubtle,
    borderRadius: radius.lg,
    overflow: 'hidden',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: space[3],
    paddingHorizontal: space[4],
    paddingVertical: space[3],
    minHeight: 44,
  },
  rowDivider: {
    borderBottomWidth: 1,
    borderBottomColor: theme.borderSubtle,
  },
  rowIcon: {
    width: 40,
    height: 40,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowText: {
    flex: 1,
  },
  rowTitle: {
    fontSize: 15,
    fontFamily: 'Urbanist_600SemiBold',
    color: theme.textPrimary,
  },
  rowSubtitle: {
    fontSize: 12,
    fontFamily: 'Urbanist_500Medium',
    color: theme.textSecondary,
    marginTop: 2,
  },
});
